apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.selectorAppLabel }}
  template:
    metadata:
      labels:
        app: {{ .Values.selectorAppLabel }}
    spec:
      containers:
        - name: {{ .Values.deployment.name }}
          image: {{ .Values.image.repository }}
          args:
            {{- range .Values.containerArgs }}
            - {{ . | quote }}
            {{- end }}
          ports:
            - containerPort: {{ .Values.containerPort }}
